# Generated by Django 4.1.1 on 2022-10-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querys',
            name='respuesta',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
