# Generated by Django 4.1.1 on 2022-10-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAI', '0002_querys_respuesta_delete_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querys',
            name='respuesta',
            field=models.CharField(blank=True, default='some_value', max_length=400),
        ),
    ]
