# Generated by Django 4.1.1 on 2022-10-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAI', '0003_alter_querys_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querys',
            name='respuesta',
            field=models.CharField(auto_created=True, blank=True, default='some_value', max_length=400),
        ),
    ]
