# Generated by Django 4.1.1 on 2022-10-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAI', '0005_alter_querys_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querys',
            name='consulta',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
